-- LOCAL DEVELOPMENT ONLY. NEVER run this file with --remote, and never add it to migrations, seed.sql or CI.
-- Sample website content (LANDING_V1 §4); every record and section is sample: true and must be replaced before launch.
-- Generated by backend/cloudflare/scripts/export-sample-website-sql.mjs from backend/shared/sampleWebsite.js.
-- Apply with: npm run d1:seed:sample:local (wrangler d1 execute juwon-electric --local --file seeds/sample-website.sql)

-- faqs
INSERT INTO records (id, collection, slug, data, is_active, sort_order, created_at, updated_at)
  VALUES ('sample-faq-1', 'faqs', NULL, '{"id":"sample-faq-1","question":"Do I pay to place an order?","answer":"No. Placing an order on our website is free. After you order, our team calls you to confirm the details and arrange payment with you.","category":"Ordering","sortOrder":1,"isActive":true,"sample":true,"createdAt":"2026-09-17T08:00:00.000Z","updatedAt":"2026-09-17T08:00:00.000Z"}', 1, 1, '2026-09-17T08:00:00.000Z', '2026-09-17T08:00:00.000Z')
  ON CONFLICT (id) DO UPDATE SET data = json_set(excluded.data, '$.createdAt', json_extract(records.data, '$.createdAt')),
    is_active = excluded.is_active, sort_order = excluded.sort_order, updated_at = excluded.updated_at
  WHERE records.collection = 'faqs' AND json_extract(records.data, '$.sample') = 1;
INSERT INTO records (id, collection, slug, data, is_active, sort_order, created_at, updated_at)
  VALUES ('sample-faq-2', 'faqs', NULL, '{"id":"sample-faq-2","question":"How long does installation take?","answer":"Most home systems are installed and tested in one day. Larger systems with many panels can take two to three days. Your engineer confirms the timeline with you before the visit.","category":"Installation","sortOrder":2,"isActive":true,"sample":true,"createdAt":"2026-09-17T08:00:01.000Z","updatedAt":"2026-09-17T08:00:01.000Z"}', 1, 2, '2026-09-17T08:00:01.000Z', '2026-09-17T08:00:01.000Z')
  ON CONFLICT (id) DO UPDATE SET data = json_set(excluded.data, '$.createdAt', json_extract(records.data, '$.createdAt')),
    is_active = excluded.is_active, sort_order = excluded.sort_order, updated_at = excluded.updated_at
  WHERE records.collection = 'faqs' AND json_extract(records.data, '$.sample') = 1;
INSERT INTO records (id, collection, slug, data, is_active, sort_order, created_at, updated_at)
  VALUES ('sample-faq-3', 'faqs', NULL, '{"id":"sample-faq-3","question":"Can I buy a single battery or inverter?","answer":"Yes. Inverters, batteries and solar panels are sold individually on the Products page. Add what you need to your cart and order it the same way as a package.","category":"Products","sortOrder":3,"isActive":true,"sample":true,"createdAt":"2026-09-17T08:00:02.000Z","updatedAt":"2026-09-17T08:00:02.000Z"}', 1, 3, '2026-09-17T08:00:02.000Z', '2026-09-17T08:00:02.000Z')
  ON CONFLICT (id) DO UPDATE SET data = json_set(excluded.data, '$.createdAt', json_extract(records.data, '$.createdAt')),
    is_active = excluded.is_active, sort_order = excluded.sort_order, updated_at = excluded.updated_at
  WHERE records.collection = 'faqs' AND json_extract(records.data, '$.sample') = 1;
INSERT INTO records (id, collection, slug, data, is_active, sort_order, created_at, updated_at)
  VALUES ('sample-faq-4', 'faqs', NULL, '{"id":"sample-faq-4","question":"What''s the difference between tubular and lithium batteries?","answer":"Tubular batteries cost less up front but are heavier, need a ventilated space and regular water top-ups.\nLithium batteries cost more but are lighter, need no maintenance, charge faster and last for many more charge cycles.\nEvery product page lists the battery''s full specs.","category":"Products","sortOrder":4,"isActive":true,"sample":true,"createdAt":"2026-09-17T08:00:03.000Z","updatedAt":"2026-09-17T08:00:03.000Z"}', 1, 4, '2026-09-17T08:00:03.000Z', '2026-09-17T08:00:03.000Z')
  ON CONFLICT (id) DO UPDATE SET data = json_set(excluded.data, '$.createdAt', json_extract(records.data, '$.createdAt')),
    is_active = excluded.is_active, sort_order = excluded.sort_order, updated_at = excluded.updated_at
  WHERE records.collection = 'faqs' AND json_extract(records.data, '$.sample') = 1;
INSERT INTO records (id, collection, slug, data, is_active, sort_order, created_at, updated_at)
  VALUES ('sample-faq-5', 'faqs', NULL, '{"id":"sample-faq-5","question":"Which states do you cover?","answer":"We deliver and install across Nigeria. Delivery and installation costs depend on your location, and we confirm them with you on the confirmation call.","category":"Installation","sortOrder":5,"isActive":true,"sample":true,"createdAt":"2026-09-17T08:00:04.000Z","updatedAt":"2026-09-17T08:00:04.000Z"}', 1, 5, '2026-09-17T08:00:04.000Z', '2026-09-17T08:00:04.000Z')
  ON CONFLICT (id) DO UPDATE SET data = json_set(excluded.data, '$.createdAt', json_extract(records.data, '$.createdAt')),
    is_active = excluded.is_active, sort_order = excluded.sort_order, updated_at = excluded.updated_at
  WHERE records.collection = 'faqs' AND json_extract(records.data, '$.sample') = 1;
INSERT INTO records (id, collection, slug, data, is_active, sort_order, created_at, updated_at)
  VALUES ('sample-faq-6', 'faqs', NULL, '{"id":"sample-faq-6","question":"What happens after I order?","answer":"1. We call you to confirm your order and arrange payment.\n2. We prepare your equipment.\n3. Your order goes out for delivery.\n4. When your order includes installation, our engineers install and test the system after delivery.\nYou can call us at any step.","category":"Ordering","sortOrder":6,"isActive":true,"sample":true,"createdAt":"2026-09-17T08:00:05.000Z","updatedAt":"2026-09-17T08:00:05.000Z"}', 1, 6, '2026-09-17T08:00:05.000Z', '2026-09-17T08:00:05.000Z')
  ON CONFLICT (id) DO UPDATE SET data = json_set(excluded.data, '$.createdAt', json_extract(records.data, '$.createdAt')),
    is_active = excluded.is_active, sort_order = excluded.sort_order, updated_at = excluded.updated_at
  WHERE records.collection = 'faqs' AND json_extract(records.data, '$.sample') = 1;
INSERT INTO records (id, collection, slug, data, is_active, sort_order, created_at, updated_at)
  VALUES ('sample-faq-7', 'faqs', NULL, '{"id":"sample-faq-7","question":"Can I add solar panels later?","answer":"Yes. Many customers start with an inverter and batteries and add panels later. Our packages come with and without solar, so tell us your plans when we call and we''ll recommend an inverter that can take panels later.","category":"Products","sortOrder":7,"isActive":true,"sample":true,"createdAt":"2026-09-17T08:00:06.000Z","updatedAt":"2026-09-17T08:00:06.000Z"}', 1, 7, '2026-09-17T08:00:06.000Z', '2026-09-17T08:00:06.000Z')
  ON CONFLICT (id) DO UPDATE SET data = json_set(excluded.data, '$.createdAt', json_extract(records.data, '$.createdAt')),
    is_active = excluded.is_active, sort_order = excluded.sort_order, updated_at = excluded.updated_at
  WHERE records.collection = 'faqs' AND json_extract(records.data, '$.sample') = 1;
INSERT INTO records (id, collection, slug, data, is_active, sort_order, created_at, updated_at)
  VALUES ('sample-faq-8', 'faqs', NULL, '{"id":"sample-faq-8","question":"How do I choose a package size?","answer":"Use our solar calculator: pick the appliances you want to power and it estimates the inverter size, batteries and panels you need, then shows matching packages. If you''re not sure, talk to an engineer and we''ll recommend a size before installation.","category":"Ordering","sortOrder":8,"isActive":true,"sample":true,"createdAt":"2026-09-17T08:00:07.000Z","updatedAt":"2026-09-17T08:00:07.000Z"}', 1, 8, '2026-09-17T08:00:07.000Z', '2026-09-17T08:00:07.000Z')
  ON CONFLICT (id) DO UPDATE SET data = json_set(excluded.data, '$.createdAt', json_extract(records.data, '$.createdAt')),
    is_active = excluded.is_active, sort_order = excluded.sort_order, updated_at = excluded.updated_at
  WHERE records.collection = 'faqs' AND json_extract(records.data, '$.sample') = 1;

-- testimonials
INSERT INTO records (id, collection, slug, data, is_active, sort_order, created_at, updated_at)
  VALUES ('sample-review-1', 'testimonials', NULL, '{"id":"sample-review-1","name":"Adaeze O.","context":"3.5kVA lithium, Ikeja","quote":"I ordered on the website late at night and got a call the next morning to confirm everything. No payment until they called. Installation was done the same week.","rating":5,"source":"google","imageUrl":null,"sortOrder":1,"isActive":true,"sample":true,"createdAt":"2026-09-17T08:00:00.000Z","updatedAt":"2026-09-17T08:00:00.000Z"}', 1, 1, '2026-09-17T08:00:00.000Z', '2026-09-17T08:00:00.000Z')
  ON CONFLICT (id) DO UPDATE SET data = json_set(excluded.data, '$.createdAt', json_extract(records.data, '$.createdAt')),
    is_active = excluded.is_active, sort_order = excluded.sort_order, updated_at = excluded.updated_at
  WHERE records.collection = 'testimonials' AND json_extract(records.data, '$.sample') = 1;
INSERT INTO records (id, collection, slug, data, is_active, sort_order, created_at, updated_at)
  VALUES ('sample-review-2', 'testimonials', NULL, '{"id":"sample-review-2","name":"Tunde B.","context":"5kVA tubular system, Surulere","quote":"NEPA took light for three days on our street and my house stayed on the whole time. The engineers explained how to check the batteries before they left.","rating":5,"source":"whatsapp","imageUrl":null,"sortOrder":2,"isActive":true,"sample":true,"createdAt":"2026-09-17T08:00:01.000Z","updatedAt":"2026-09-17T08:00:01.000Z"}', 1, 2, '2026-09-17T08:00:01.000Z', '2026-09-17T08:00:01.000Z')
  ON CONFLICT (id) DO UPDATE SET data = json_set(excluded.data, '$.createdAt', json_extract(records.data, '$.createdAt')),
    is_active = excluded.is_active, sort_order = excluded.sort_order, updated_at = excluded.updated_at
  WHERE records.collection = 'testimonials' AND json_extract(records.data, '$.sample') = 1;
INSERT INTO records (id, collection, slug, data, is_active, sort_order, created_at, updated_at)
  VALUES ('sample-review-3', 'testimonials', NULL, '{"id":"sample-review-3","name":"Chioma E.","context":"2.5kVA inverter and batteries, Lekki","quote":"The calculator helped me see that I didn''t need a big system for my flat. The team confirmed the size on the call and the installation was neat and quick.","rating":4,"source":"website","imageUrl":null,"sortOrder":3,"isActive":true,"sample":true,"createdAt":"2026-09-17T08:00:02.000Z","updatedAt":"2026-09-17T08:00:02.000Z"}', 1, 3, '2026-09-17T08:00:02.000Z', '2026-09-17T08:00:02.000Z')
  ON CONFLICT (id) DO UPDATE SET data = json_set(excluded.data, '$.createdAt', json_extract(records.data, '$.createdAt')),
    is_active = excluded.is_active, sort_order = excluded.sort_order, updated_at = excluded.updated_at
  WHERE records.collection = 'testimonials' AND json_extract(records.data, '$.sample') = 1;
INSERT INTO records (id, collection, slug, data, is_active, sort_order, created_at, updated_at)
  VALUES ('sample-review-4', 'testimonials', NULL, '{"id":"sample-review-4","name":"Ibrahim M.","context":"10kVA lithium with solar, Abuja","quote":"We run our small office on solar during the day now. Delivery to Abuja was arranged on the confirmation call and the engineers tested every circuit.","rating":5,"source":"in_person","imageUrl":null,"sortOrder":4,"isActive":true,"sample":true,"createdAt":"2026-09-17T08:00:03.000Z","updatedAt":"2026-09-17T08:00:03.000Z"}', 1, 4, '2026-09-17T08:00:03.000Z', '2026-09-17T08:00:03.000Z')
  ON CONFLICT (id) DO UPDATE SET data = json_set(excluded.data, '$.createdAt', json_extract(records.data, '$.createdAt')),
    is_active = excluded.is_active, sort_order = excluded.sort_order, updated_at = excluded.updated_at
  WHERE records.collection = 'testimonials' AND json_extract(records.data, '$.sample') = 1;
INSERT INTO records (id, collection, slug, data, is_active, sort_order, created_at, updated_at)
  VALUES ('sample-review-5', 'testimonials', NULL, '{"id":"sample-review-5","name":"Folake A.","context":"Clinic backup system, Ibadan","quote":"Our clinic fridge and lights no longer go off when the grid fails. The engineers came back after a month to check the system without us asking.","rating":4,"source":"facebook","imageUrl":null,"sortOrder":5,"isActive":true,"sample":true,"createdAt":"2026-09-17T08:00:04.000Z","updatedAt":"2026-09-17T08:00:04.000Z"}', 1, 5, '2026-09-17T08:00:04.000Z', '2026-09-17T08:00:04.000Z')
  ON CONFLICT (id) DO UPDATE SET data = json_set(excluded.data, '$.createdAt', json_extract(records.data, '$.createdAt')),
    is_active = excluded.is_active, sort_order = excluded.sort_order, updated_at = excluded.updated_at
  WHERE records.collection = 'testimonials' AND json_extract(records.data, '$.sample') = 1;
INSERT INTO records (id, collection, slug, data, is_active, sort_order, created_at, updated_at)
  VALUES ('sample-review-6', 'testimonials', NULL, '{"id":"sample-review-6","name":"Emeka N.","context":"Single lithium battery, Kano","quote":"I only needed one extra battery for my existing inverter. I found it on the Products page, ordered it, and they called within the hour to confirm.","rating":5,"source":"website","imageUrl":null,"sortOrder":6,"isActive":true,"sample":true,"createdAt":"2026-09-17T08:00:05.000Z","updatedAt":"2026-09-17T08:00:05.000Z"}', 1, 6, '2026-09-17T08:00:05.000Z', '2026-09-17T08:00:05.000Z')
  ON CONFLICT (id) DO UPDATE SET data = json_set(excluded.data, '$.createdAt', json_extract(records.data, '$.createdAt')),
    is_active = excluded.is_active, sort_order = excluded.sort_order, updated_at = excluded.updated_at
  WHERE records.collection = 'testimonials' AND json_extract(records.data, '$.sample') = 1;

-- clients
INSERT INTO records (id, collection, slug, data, is_active, sort_order, created_at, updated_at)
  VALUES ('sample-client-1', 'clients', NULL, '{"id":"sample-client-1","name":"Lagoon View Clinic","logoUrl":"/samples/client-1.svg","website":null,"sortOrder":1,"isActive":true,"sample":true,"createdAt":"2026-09-17T08:00:00.000Z","updatedAt":"2026-09-17T08:00:00.000Z"}', 1, 1, '2026-09-17T08:00:00.000Z', '2026-09-17T08:00:00.000Z')
  ON CONFLICT (id) DO UPDATE SET data = json_set(excluded.data, '$.createdAt', json_extract(records.data, '$.createdAt')),
    is_active = excluded.is_active, sort_order = excluded.sort_order, updated_at = excluded.updated_at
  WHERE records.collection = 'clients' AND json_extract(records.data, '$.sample') = 1;
INSERT INTO records (id, collection, slug, data, is_active, sort_order, created_at, updated_at)
  VALUES ('sample-client-2', 'clients', NULL, '{"id":"sample-client-2","name":"Crestfield Academy","logoUrl":"/samples/client-2.svg","website":null,"sortOrder":2,"isActive":true,"sample":true,"createdAt":"2026-09-17T08:00:01.000Z","updatedAt":"2026-09-17T08:00:01.000Z"}', 1, 2, '2026-09-17T08:00:01.000Z', '2026-09-17T08:00:01.000Z')
  ON CONFLICT (id) DO UPDATE SET data = json_set(excluded.data, '$.createdAt', json_extract(records.data, '$.createdAt')),
    is_active = excluded.is_active, sort_order = excluded.sort_order, updated_at = excluded.updated_at
  WHERE records.collection = 'clients' AND json_extract(records.data, '$.sample') = 1;
INSERT INTO records (id, collection, slug, data, is_active, sort_order, created_at, updated_at)
  VALUES ('sample-client-3', 'clients', NULL, '{"id":"sample-client-3","name":"Palmgrove Farms","logoUrl":"/samples/client-3.svg","website":null,"sortOrder":3,"isActive":true,"sample":true,"createdAt":"2026-09-17T08:00:02.000Z","updatedAt":"2026-09-17T08:00:02.000Z"}', 1, 3, '2026-09-17T08:00:02.000Z', '2026-09-17T08:00:02.000Z')
  ON CONFLICT (id) DO UPDATE SET data = json_set(excluded.data, '$.createdAt', json_extract(records.data, '$.createdAt')),
    is_active = excluded.is_active, sort_order = excluded.sort_order, updated_at = excluded.updated_at
  WHERE records.collection = 'clients' AND json_extract(records.data, '$.sample') = 1;
INSERT INTO records (id, collection, slug, data, is_active, sort_order, created_at, updated_at)
  VALUES ('sample-client-4', 'clients', NULL, '{"id":"sample-client-4","name":"Northbridge Microfinance","logoUrl":"/samples/client-4.svg","website":null,"sortOrder":4,"isActive":true,"sample":true,"createdAt":"2026-09-17T08:00:03.000Z","updatedAt":"2026-09-17T08:00:03.000Z"}', 1, 4, '2026-09-17T08:00:03.000Z', '2026-09-17T08:00:03.000Z')
  ON CONFLICT (id) DO UPDATE SET data = json_set(excluded.data, '$.createdAt', json_extract(records.data, '$.createdAt')),
    is_active = excluded.is_active, sort_order = excluded.sort_order, updated_at = excluded.updated_at
  WHERE records.collection = 'clients' AND json_extract(records.data, '$.sample') = 1;
INSERT INTO records (id, collection, slug, data, is_active, sort_order, created_at, updated_at)
  VALUES ('sample-client-5', 'clients', NULL, '{"id":"sample-client-5","name":"Unity Court Residents","logoUrl":"/samples/client-5.svg","website":null,"sortOrder":5,"isActive":true,"sample":true,"createdAt":"2026-09-17T08:00:04.000Z","updatedAt":"2026-09-17T08:00:04.000Z"}', 1, 5, '2026-09-17T08:00:04.000Z', '2026-09-17T08:00:04.000Z')
  ON CONFLICT (id) DO UPDATE SET data = json_set(excluded.data, '$.createdAt', json_extract(records.data, '$.createdAt')),
    is_active = excluded.is_active, sort_order = excluded.sort_order, updated_at = excluded.updated_at
  WHERE records.collection = 'clients' AND json_extract(records.data, '$.sample') = 1;
INSERT INTO records (id, collection, slug, data, is_active, sort_order, created_at, updated_at)
  VALUES ('sample-client-6', 'clients', NULL, '{"id":"sample-client-6","name":"Brightpath Logistics","logoUrl":"/samples/client-6.svg","website":null,"sortOrder":6,"isActive":true,"sample":true,"createdAt":"2026-09-17T08:00:05.000Z","updatedAt":"2026-09-17T08:00:05.000Z"}', 1, 6, '2026-09-17T08:00:05.000Z', '2026-09-17T08:00:05.000Z')
  ON CONFLICT (id) DO UPDATE SET data = json_set(excluded.data, '$.createdAt', json_extract(records.data, '$.createdAt')),
    is_active = excluded.is_active, sort_order = excluded.sort_order, updated_at = excluded.updated_at
  WHERE records.collection = 'clients' AND json_extract(records.data, '$.sample') = 1;

-- teamMembers
INSERT INTO records (id, collection, slug, data, is_active, sort_order, created_at, updated_at)
  VALUES ('sample-team-1', 'teamMembers', NULL, '{"id":"sample-team-1","name":"Adebayo Ogunleye","role":"Managing director","group":"Leadership","bio":"Leads the business and signs off every large installation before it is handed over to the customer.","photoUrl":"/samples/team/member-1.svg","linkedinUrl":null,"sortOrder":1,"isActive":true,"sample":true,"createdAt":"2026-09-17T08:00:00.000Z","updatedAt":"2026-09-17T08:00:00.000Z"}', 1, 1, '2026-09-17T08:00:00.000Z', '2026-09-17T08:00:00.000Z')
  ON CONFLICT (id) DO UPDATE SET data = json_set(excluded.data, '$.createdAt', json_extract(records.data, '$.createdAt')),
    is_active = excluded.is_active, sort_order = excluded.sort_order, updated_at = excluded.updated_at
  WHERE records.collection = 'teamMembers' AND json_extract(records.data, '$.sample') = 1;
INSERT INTO records (id, collection, slug, data, is_active, sort_order, created_at, updated_at)
  VALUES ('sample-team-2', 'teamMembers', NULL, '{"id":"sample-team-2","name":"Chiamaka Nwosu","role":"Head of engineering","group":"Leadership","bio":"Reviews the sizing behind every quote so each customer gets an inverter and battery bank that fits their load.","photoUrl":"/samples/team/member-2.svg","linkedinUrl":null,"sortOrder":2,"isActive":true,"sample":true,"createdAt":"2026-09-17T08:00:01.000Z","updatedAt":"2026-09-17T08:00:01.000Z"}', 1, 2, '2026-09-17T08:00:01.000Z', '2026-09-17T08:00:01.000Z')
  ON CONFLICT (id) DO UPDATE SET data = json_set(excluded.data, '$.createdAt', json_extract(records.data, '$.createdAt')),
    is_active = excluded.is_active, sort_order = excluded.sort_order, updated_at = excluded.updated_at
  WHERE records.collection = 'teamMembers' AND json_extract(records.data, '$.sample') = 1;
INSERT INTO records (id, collection, slug, data, is_active, sort_order, created_at, updated_at)
  VALUES ('sample-team-3', 'teamMembers', NULL, '{"id":"sample-team-3","name":"Ifeanyi Obi","role":"Lead installation engineer","group":"Engineering & installations","bio":"Plans installation days and leads the crew that mounts panels, wires inverters and tests each system.","photoUrl":"/samples/team/member-3.svg","linkedinUrl":null,"sortOrder":3,"isActive":true,"sample":true,"createdAt":"2026-09-17T08:00:02.000Z","updatedAt":"2026-09-17T08:00:02.000Z"}', 1, 3, '2026-09-17T08:00:02.000Z', '2026-09-17T08:00:02.000Z')
  ON CONFLICT (id) DO UPDATE SET data = json_set(excluded.data, '$.createdAt', json_extract(records.data, '$.createdAt')),
    is_active = excluded.is_active, sort_order = excluded.sort_order, updated_at = excluded.updated_at
  WHERE records.collection = 'teamMembers' AND json_extract(records.data, '$.sample') = 1;
INSERT INTO records (id, collection, slug, data, is_active, sort_order, created_at, updated_at)
  VALUES ('sample-team-4', 'teamMembers', NULL, '{"id":"sample-team-4","name":"Kehinde Alabi","role":"Solar design engineer","group":"Engineering & installations","bio":"Sizes systems from customers'' appliance lists and site visits, then lays out the panels and batteries.","photoUrl":"/samples/team/member-4.svg","linkedinUrl":null,"sortOrder":4,"isActive":true,"sample":true,"createdAt":"2026-09-17T08:00:03.000Z","updatedAt":"2026-09-17T08:00:03.000Z"}', 1, 4, '2026-09-17T08:00:03.000Z', '2026-09-17T08:00:03.000Z')
  ON CONFLICT (id) DO UPDATE SET data = json_set(excluded.data, '$.createdAt', json_extract(records.data, '$.createdAt')),
    is_active = excluded.is_active, sort_order = excluded.sort_order, updated_at = excluded.updated_at
  WHERE records.collection = 'teamMembers' AND json_extract(records.data, '$.sample') = 1;
INSERT INTO records (id, collection, slug, data, is_active, sort_order, created_at, updated_at)
  VALUES ('sample-team-5', 'teamMembers', NULL, '{"id":"sample-team-5","name":"Musa Danjuma","role":"Installation technician","group":"Engineering & installations","bio":"Installs inverters and batteries and walks customers through their new system before leaving the site.","photoUrl":"/samples/team/member-5.svg","linkedinUrl":null,"sortOrder":5,"isActive":true,"sample":true,"createdAt":"2026-09-17T08:00:04.000Z","updatedAt":"2026-09-17T08:00:04.000Z"}', 1, 5, '2026-09-17T08:00:04.000Z', '2026-09-17T08:00:04.000Z')
  ON CONFLICT (id) DO UPDATE SET data = json_set(excluded.data, '$.createdAt', json_extract(records.data, '$.createdAt')),
    is_active = excluded.is_active, sort_order = excluded.sort_order, updated_at = excluded.updated_at
  WHERE records.collection = 'teamMembers' AND json_extract(records.data, '$.sample') = 1;
INSERT INTO records (id, collection, slug, data, is_active, sort_order, created_at, updated_at)
  VALUES ('sample-team-6', 'teamMembers', NULL, '{"id":"sample-team-6","name":"Tolulope Akinwale","role":"Electrical technician","group":"Engineering & installations","bio":"Handles changeover wiring and earthing so every system switches cleanly between the grid and backup.","photoUrl":"/samples/team/member-6.svg","linkedinUrl":null,"sortOrder":6,"isActive":true,"sample":true,"createdAt":"2026-09-17T08:00:05.000Z","updatedAt":"2026-09-17T08:00:05.000Z"}', 1, 6, '2026-09-17T08:00:05.000Z', '2026-09-17T08:00:05.000Z')
  ON CONFLICT (id) DO UPDATE SET data = json_set(excluded.data, '$.createdAt', json_extract(records.data, '$.createdAt')),
    is_active = excluded.is_active, sort_order = excluded.sort_order, updated_at = excluded.updated_at
  WHERE records.collection = 'teamMembers' AND json_extract(records.data, '$.sample') = 1;
INSERT INTO records (id, collection, slug, data, is_active, sort_order, created_at, updated_at)
  VALUES ('sample-team-7', 'teamMembers', NULL, '{"id":"sample-team-7","name":"Blessing Okafor","role":"Sales lead","group":"Sales & customer care","bio":"Helps customers choose the right package and explains what each system can power in their home or office.","photoUrl":"/samples/team/member-7.svg","linkedinUrl":null,"sortOrder":7,"isActive":true,"sample":true,"createdAt":"2026-09-17T08:00:06.000Z","updatedAt":"2026-09-17T08:00:06.000Z"}', 1, 7, '2026-09-17T08:00:06.000Z', '2026-09-17T08:00:06.000Z')
  ON CONFLICT (id) DO UPDATE SET data = json_set(excluded.data, '$.createdAt', json_extract(records.data, '$.createdAt')),
    is_active = excluded.is_active, sort_order = excluded.sort_order, updated_at = excluded.updated_at
  WHERE records.collection = 'teamMembers' AND json_extract(records.data, '$.sample') = 1;
INSERT INTO records (id, collection, slug, data, is_active, sort_order, created_at, updated_at)
  VALUES ('sample-team-8', 'teamMembers', NULL, '{"id":"sample-team-8","name":"Yetunde Salami","role":"Customer care officer","group":"Sales & customer care","bio":"Makes the confirmation call after each order and keeps customers updated from processing to delivery.","photoUrl":"/samples/team/member-8.svg","linkedinUrl":null,"sortOrder":8,"isActive":true,"sample":true,"createdAt":"2026-09-17T08:00:07.000Z","updatedAt":"2026-09-17T08:00:07.000Z"}', 1, 8, '2026-09-17T08:00:07.000Z', '2026-09-17T08:00:07.000Z')
  ON CONFLICT (id) DO UPDATE SET data = json_set(excluded.data, '$.createdAt', json_extract(records.data, '$.createdAt')),
    is_active = excluded.is_active, sort_order = excluded.sort_order, updated_at = excluded.updated_at
  WHERE records.collection = 'teamMembers' AND json_extract(records.data, '$.sample') = 1;
INSERT INTO records (id, collection, slug, data, is_active, sort_order, created_at, updated_at)
  VALUES ('sample-team-9', 'teamMembers', NULL, '{"id":"sample-team-9","name":"Emmanuel Udoh","role":"After-sales support officer","group":"Sales & customer care","bio":"Books maintenance visits and follows up on battery and inverter questions after installation.","photoUrl":"/samples/team/member-9.svg","linkedinUrl":null,"sortOrder":9,"isActive":true,"sample":true,"createdAt":"2026-09-17T08:00:08.000Z","updatedAt":"2026-09-17T08:00:08.000Z"}', 1, 9, '2026-09-17T08:00:08.000Z', '2026-09-17T08:00:08.000Z')
  ON CONFLICT (id) DO UPDATE SET data = json_set(excluded.data, '$.createdAt', json_extract(records.data, '$.createdAt')),
    is_active = excluded.is_active, sort_order = excluded.sort_order, updated_at = excluded.updated_at
  WHERE records.collection = 'teamMembers' AND json_extract(records.data, '$.sample') = 1;
INSERT INTO records (id, collection, slug, data, is_active, sort_order, created_at, updated_at)
  VALUES ('sample-team-10', 'teamMembers', NULL, '{"id":"sample-team-10","name":"Aisha Bello","role":"Operations manager","group":"Operations","bio":"Coordinates stock, delivery and installation dates so every order moves through fulfilment on time.","photoUrl":"/samples/team/member-10.svg","linkedinUrl":null,"sortOrder":10,"isActive":true,"sample":true,"createdAt":"2026-09-17T08:00:09.000Z","updatedAt":"2026-09-17T08:00:09.000Z"}', 1, 10, '2026-09-17T08:00:09.000Z', '2026-09-17T08:00:09.000Z')
  ON CONFLICT (id) DO UPDATE SET data = json_set(excluded.data, '$.createdAt', json_extract(records.data, '$.createdAt')),
    is_active = excluded.is_active, sort_order = excluded.sort_order, updated_at = excluded.updated_at
  WHERE records.collection = 'teamMembers' AND json_extract(records.data, '$.sample') = 1;
INSERT INTO records (id, collection, slug, data, is_active, sort_order, created_at, updated_at)
  VALUES ('sample-team-11', 'teamMembers', NULL, '{"id":"sample-team-11","name":"Segun Oladipo","role":"Logistics coordinator","group":"Operations","bio":"Arranges delivery of panels, inverters and batteries to customers'' sites across Nigeria.","photoUrl":"/samples/team/member-11.svg","linkedinUrl":null,"sortOrder":11,"isActive":true,"sample":true,"createdAt":"2026-09-17T08:00:10.000Z","updatedAt":"2026-09-17T08:00:10.000Z"}', 1, 11, '2026-09-17T08:00:10.000Z', '2026-09-17T08:00:10.000Z')
  ON CONFLICT (id) DO UPDATE SET data = json_set(excluded.data, '$.createdAt', json_extract(records.data, '$.createdAt')),
    is_active = excluded.is_active, sort_order = excluded.sort_order, updated_at = excluded.updated_at
  WHERE records.collection = 'teamMembers' AND json_extract(records.data, '$.sample') = 1;
INSERT INTO records (id, collection, slug, data, is_active, sort_order, created_at, updated_at)
  VALUES ('sample-team-12', 'teamMembers', NULL, '{"id":"sample-team-12","name":"Halima Yusuf","role":"Inventory officer","group":"Operations","bio":"Keeps stock counts accurate so the prices and availability shown on the website stay current.","photoUrl":"/samples/team/member-12.svg","linkedinUrl":null,"sortOrder":12,"isActive":true,"sample":true,"createdAt":"2026-09-17T08:00:11.000Z","updatedAt":"2026-09-17T08:00:11.000Z"}', 1, 12, '2026-09-17T08:00:11.000Z', '2026-09-17T08:00:11.000Z')
  ON CONFLICT (id) DO UPDATE SET data = json_set(excluded.data, '$.createdAt', json_extract(records.data, '$.createdAt')),
    is_active = excluded.is_active, sort_order = excluded.sort_order, updated_at = excluded.updated_at
  WHERE records.collection = 'teamMembers' AND json_extract(records.data, '$.sample') = 1;

-- portfolio case-study fields (existing records, by id)
UPDATE records SET data = json_set(data,
    '$.category', 'academic-institutions', '$.summary', 'Daytime solar for a primary school''s classrooms and staff room, so lessons no longer stop when the grid goes off.', '$.location', 'Ikorodu, Lagos', '$.system', '5kVA inverter, 4 × 200Ah tubular batteries, 4 × 550W panels',
    '$.sample', json('true'))
  WHERE collection = 'portfolio' AND id = '4aa57972-706d-4a7a-81af-b5e8b7f9766a' AND COALESCE(json_extract(data, '$.sample'), 1) = 1;
UPDATE records SET data = json_set(data,
    '$.category', 'hospitals', '$.summary', 'Backup power for a clinic''s consulting rooms, vaccine fridge and lighting, switching over without a break.', '$.location', 'Surulere, Lagos', '$.system', '7.5kVA inverter, 2 × 5kWh lithium batteries',
    '$.sample', json('true'))
  WHERE collection = 'portfolio' AND id = 'ebc263ec-8266-4a3f-8a9a-ab49b0eb891f' AND COALESCE(json_extract(data, '$.sample'), 1) = 1;
UPDATE records SET data = json_set(data,
    '$.category', 'community', '$.summary', 'Shared backup for an estate gatehouse, security lights and CCTV through the night.', '$.location', 'Ikeja, Lagos', '$.system', '5kVA inverter, 4 × 220Ah tubular batteries',
    '$.sample', json('true'))
  WHERE collection = 'portfolio' AND id = '7566f276-5fc8-43aa-b043-3e6193c94558' AND COALESCE(json_extract(data, '$.sample'), 1) = 1;
UPDATE records SET data = json_set(data,
    '$.category', 'farms', '$.summary', 'Solar power for a poultry farm''s lighting and water pump, cutting daily generator use.', '$.location', 'Wuse, Abuja', '$.system', '3kVA inverter, 2 × 200Ah tubular batteries, 3 × 400W panels',
    '$.sample', json('true'))
  WHERE collection = 'portfolio' AND id = '27148cbc-5fb8-4beb-92f4-4448b9689f06' AND COALESCE(json_extract(data, '$.sample'), 1) = 1;
UPDATE records SET data = json_set(data,
    '$.category', 'community', '$.summary', 'A compact backup system for a community centre''s hall lighting, fans and sound system.', '$.location', 'Yaba, Lagos', '$.system', '3.5kVA inverter, 2 × 220Ah tubular batteries',
    '$.sample', json('true'))
  WHERE collection = 'portfolio' AND id = '5ae9fa72-1d40-4eb2-90ba-855523897bbc' AND COALESCE(json_extract(data, '$.sample'), 1) = 1;
UPDATE records SET data = json_set(data,
    '$.category', 'government-institutions', '$.summary', 'Solar and storage for a local government records office, keeping computers and air conditioning running in office hours.', '$.location', 'Port Harcourt, Rivers', '$.system', '15kVA inverter, 4 × 10kWh lithium batteries, 16 × 550W panels',
    '$.sample', json('true'))
  WHERE collection = 'portfolio' AND id = '63e34b6b-7830-4053-ba14-6cb01f4ee089' AND COALESCE(json_extract(data, '$.sample'), 1) = 1;
UPDATE records SET data = json_set(data,
    '$.category', 'academic-institutions', '$.summary', 'Solar power for a secondary school''s computer lab, so practical classes run on schedule.', '$.location', 'Abeokuta, Ogun', '$.system', '5kVA inverter, 2 × 5kWh lithium batteries, 4 × 550W panels',
    '$.sample', json('true'))
  WHERE collection = 'portfolio' AND id = '1225e47f-c417-4e3e-b535-8626010c1e4b' AND COALESCE(json_extract(data, '$.sample'), 1) = 1;
UPDATE records SET data = json_set(data,
    '$.category', 'banking-sectors', '$.summary', 'Uninterrupted power for a microfinance branch''s servers, ATM and banking hall.', '$.location', 'Victoria Island, Lagos', '$.system', '10kVA inverter, 3 × 5kWh lithium batteries',
    '$.sample', json('true'))
  WHERE collection = 'portfolio' AND id = 'c99d942b-59ff-4ed8-a87f-8168a9139c14' AND COALESCE(json_extract(data, '$.sample'), 1) = 1;
UPDATE records SET data = json_set(data,
    '$.category', 'farms', '$.summary', 'A solar-powered borehole pump and cold room lighting for a vegetable farm.', '$.location', 'Ogun State', '$.system', '5kVA inverter, 4 × 200Ah tubular batteries, 6 × 550W panels',
    '$.sample', json('true'))
  WHERE collection = 'portfolio' AND id = 'b1cf5bed-e8aa-454d-b498-52ef888a9bbb' AND COALESCE(json_extract(data, '$.sample'), 1) = 1;
UPDATE records SET data = json_set(data,
    '$.category', 'community', '$.summary', 'Evening lighting and phone charging for a neighbourhood association''s meeting hall.', '$.location', 'Enugu, Enugu', '$.system', '2.5kVA inverter, 2 × 200Ah tubular batteries',
    '$.sample', json('true'))
  WHERE collection = 'portfolio' AND id = 'e937f944-5e9e-4cea-93be-0c2d7f27ba4f' AND COALESCE(json_extract(data, '$.sample'), 1) = 1;
UPDATE records SET data = json_set(data,
    '$.category', 'hospitals', '$.summary', 'Backup for a maternity clinic''s theatre lights, oxygen concentrators and nurses'' station.', '$.location', 'Ibadan, Oyo', '$.system', '10kVA inverter, 4 × 5kWh lithium batteries',
    '$.sample', json('true'))
  WHERE collection = 'portfolio' AND id = '5622e0d0-b8e1-4b9c-835b-c8191531626e' AND COALESCE(json_extract(data, '$.sample'), 1) = 1;
UPDATE records SET data = json_set(data,
    '$.category', 'government-institutions', '$.summary', 'Daytime solar for a public health office, reducing diesel spend on its generator.', '$.location', 'Ikeja, Lagos', '$.system', '7.5kVA inverter, 2 × 10kWh lithium batteries, 10 × 550W panels',
    '$.sample', json('true'))
  WHERE collection = 'portfolio' AND id = 'f06d012e-e026-47cd-90aa-03832e41ea14' AND COALESCE(json_extract(data, '$.sample'), 1) = 1;
UPDATE records SET data = json_set(data,
    '$.category', 'banking-sectors', '$.summary', 'Power continuity for a bank branch''s network equipment and customer service desks.', '$.location', 'Lekki, Lagos', '$.system', '10kVA inverter, 4 × 5kWh lithium batteries',
    '$.sample', json('true'))
  WHERE collection = 'portfolio' AND id = '3e6e8a4e-2b18-44ab-aa8e-9d208ce001b2' AND COALESCE(json_extract(data, '$.sample'), 1) = 1;
UPDATE records SET data = json_set(data,
    '$.category', 'academic-institutions', '$.summary', 'Night-time power for a boarding school''s hostels and study rooms.', '$.location', 'Ota, Ogun', '$.system', '7.5kVA inverter, 8 × 220Ah tubular batteries',
    '$.sample', json('true'))
  WHERE collection = 'portfolio' AND id = 'c173b02d-6f84-4630-b1d1-d789ce92fe9a' AND COALESCE(json_extract(data, '$.sample'), 1) = 1;
UPDATE records SET data = json_set(data,
    '$.category', 'farms', '$.summary', 'Solar power for a fish farm''s aerators and water circulation pumps.', '$.location', 'Benin City, Edo', '$.system', '3kVA inverter, 2 × 200Ah tubular batteries, 4 × 550W panels',
    '$.sample', json('true'))
  WHERE collection = 'portfolio' AND id = '318ec7db-aac4-4e95-b07c-1e28241acfe6' AND COALESCE(json_extract(data, '$.sample'), 1) = 1;

-- Settings: create the global document when missing, then set each sample section only while it is
-- missing, empty or still sample content (real, saved sections are kept).
INSERT INTO records (id, collection, slug, data, is_active, sort_order, created_at, updated_at)
  VALUES ('global', 'settings', NULL, '{"id":"global","updatedAt":"2026-09-17T08:00:00.000Z","updatedBy":null}', 1, 0, '2026-09-17T08:00:00.000Z', '2026-09-17T08:00:00.000Z')
  ON CONFLICT (id) DO NOTHING;
UPDATE records SET data = json_set(data, '$.website', json('{"stats":[{"label":"Installations","value":"500+"},{"label":"Years in business","value":"10+"},{"label":"Engineers","value":"25"},{"label":"Average install time","value":"1 day"}],"whatsappNumber":"+2348000000000","businessHours":"Mon–Sat 8am–6pm","productsEnabled":true,"sample":true}'))
  WHERE collection = 'settings' AND id = 'global' AND (
    json_type(data, '$.website') IS NOT 'object'
    OR json_extract(data, '$.website.sample') = 1
    OR (COALESCE(json_array_length(data, '$.website.stats'), 0) = 0 AND json_extract(data, '$.website.whatsappNumber') IS NULL AND json_extract(data, '$.website.businessHours') IS NULL)
  );
UPDATE records SET data = json_set(data, '$.financing', json('{"enabled":true,"depositPercent":40,"termsMonths":[3,6,12],"monthlyRatePercent":3.5,"approvalTime":"48 hours","note":"Sample terms — not an offer.","sample":true}'))
  WHERE collection = 'settings' AND id = 'global' AND (
    json_type(data, '$.financing') IS NOT 'object'
    OR json_extract(data, '$.financing.sample') = 1
    OR (COALESCE(json_extract(data, '$.financing.enabled'), 0) != 1 AND COALESCE(json_array_length(data, '$.financing.termsMonths'), 0) = 0 AND json_extract(data, '$.financing.depositPercent') IS NULL)
  );
UPDATE records SET data = json_set(data, '$.calculator', json('{"enabled":true,"appliances":[{"key":"fan","label":"Fan","watts":75,"defaultHours":8,"defaultQuantity":2},{"key":"led-bulb","label":"LED bulb","watts":10,"defaultHours":6,"defaultQuantity":6},{"key":"tv","label":"TV","watts":120,"defaultHours":5,"defaultQuantity":1},{"key":"decoder","label":"Decoder","watts":25,"defaultHours":5,"defaultQuantity":1},{"key":"laptop","label":"Laptop","watts":65,"defaultHours":4,"defaultQuantity":1},{"key":"phone-charging","label":"Phone charging","watts":10,"defaultHours":3,"defaultQuantity":3},{"key":"fridge","label":"Fridge","watts":150,"defaultHours":12,"defaultQuantity":1},{"key":"freezer","label":"Freezer","watts":200,"defaultHours":12,"defaultQuantity":0},{"key":"washing-machine","label":"Washing machine","watts":500,"defaultHours":1,"defaultQuantity":0},{"key":"microwave","label":"Microwave","watts":1000,"defaultHours":0.5,"defaultQuantity":0},{"key":"ac-1hp","label":"1hp air conditioner","watts":900,"defaultHours":4,"defaultQuantity":0},{"key":"pumping-machine","label":"Pumping machine","watts":750,"defaultHours":0.5,"defaultQuantity":0}],"inverterHeadroomPercent":25,"batteryDepthOfDischargePercent":80,"batteryVoltage":48,"panelWatts":550,"peakSunHours":4.5,"generator":{"fuelPricePerLitre":1000,"litresPerKvaHour":0.25,"maintenancePerMonth":20000},"sample":true}'))
  WHERE collection = 'settings' AND id = 'global' AND (
    json_type(data, '$.calculator') IS NOT 'object'
    OR json_extract(data, '$.calculator.sample') = 1
    OR (COALESCE(json_extract(data, '$.calculator.enabled'), 0) != 1 AND COALESCE(json_array_length(data, '$.calculator.appliances'), 0) = 0)
  );
